# Generated by Django 5.1.5 on 2025-02-02 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='que_bengali',
            new_name='question_bn',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='que_hindi',
            new_name='question_hi',
        ),
    ]
