# Generated by Django 5.1.5 on 2025-02-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_rename_que_bengali_faq_question_bn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer_bn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_bn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_hi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
